// resources/js/react/components/Task.js
import React, {useState} from 'react'

export default function Task() {

    const [task, setTask] = useState({})

    return (
        <li className="list-group-item flex-column align-items-start">
            <div className="d-flex w-100 justify-content-between mb-2">
                <div className="d-flex">

                    {/* Task checkbox */}
                    <div className="custom-control custom-checkbox">
                        <input type="checkbox" className="custom-control-input"/>
                        <label className="custom-control-label"></label>
                    </div>

                    {/* Task text */}
                    <h5 className="pb-0 task-text">
                        {{ task }}
                    </h5>

                </div>
                <small>Updated 3 days ago</small>
            </div>

            {/* Task actions */}
            <div>
                <button type="button" className="btn btn-link text-primary btn-sm pl-0">Edit</button>
                <button type="button" className="btn btn-link text-danger btn-sm">Delete</button>
            </div>

        </li>
    )
}

// resources/js/components/Task.vue
<template>
    <li class="list-group-item flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between mb-2">
            <div class="d-flex">

                <!-- Task checkbox -->
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" :id="`task-${todo.id}`"
                           v-model="todo.complete">
                    <label class="custom-control-label" :for="`task-${todo.id}`"></label>
                </div>

                <!-- Task text -->
                <h5 class="pb-0 task-text" :class="{'task-complete' : todo.complete}">
                    {{ todo.text }}
                </h5>

            </div>
            <small>Updated 3 days ago</small>
        </div>

        <!-- Task actions -->
        <div>
            <button type="button" class="btn btn-link text-primary btn-sm pl-0">Update</button>
            <button type="button" class="btn btn-link text-danger btn-sm" @click="deleteTask">Delete</button>
        </div>

    </li>
</template>

<script>

    export default {

        props: {

            task: {
                type: Object,
                required: true
            }

        },

        data() {
            return {
                todo: this.task
            }
        },

        methods: {

            toggleTaskCompletion() {

                //

                this.$emit('updated')
            },

            deleteTask() {

                //

                this.$emit('updated')
            }

        }

    }

</script>

<style scoped>

    .task-text {
        margin-top: 2px;
    }

    .task-complete {
        text-decoration: line-through;
    }

</style>
